[tool.poetry]
name = "key-events"
version = "0.1.0"
description = ""
authors = ["David Buckley <buckley.w.david@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
